baseURL: https://hackzurich2021-foitt.github.io/home/
disablePathToLower: true
languageCode: en-us
title: Swiss Open Data
theme: gochowdown
googleAnalytics:
defaultcontentlanguage: en
paginate: 10
canonifyurls: true
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pygmentsOptions: "linenos=table"
permalinks:
  posts: /posts/:year/:month/:title
params:
  author: Marina + Arturo
  description: Explore the Swiss Open Data of the FOITT
  keywords: 'data'
  favicon_32: /images/favicon-32x32.png
  favicon_16: /images/favicon-16x16.png
  footercontent:
  hidecredits: true
  hidecopyright: true
  showNavTitle: false            # Boolean: show site title in nav bar
  custom_css:
    - style.css
menu:
  main:
    - name: Home
      weight: 1
      url: /
    - name: Category
      weight: 2
      url: /category/
    - name: Canton
      weight: 3
      url: /canton/
    - name: Tags
      weight: 4
      url: /tags/
taxonomies:
  category: category
  canton: canton
  tag: tags
